[
  {
  "id": 101,
  "first": "Mes",
  "last": "Nas",
  "department": "Project Development"
  },
  {
  "id": 102,
  "first": "Me",
  "last": "End",
  "department": "Project Management"
  },
  {
  "id": 103,
  "first": "Ab",
  "last": "Adm",
  "department": "Project Management"
  },
  {
  "id": 104,
  "first": "Mill",
  "last": "Jo",
  "department": "Quality Assurance"
  },
   {
  "id": 105,
  "first": "Ad",
  "last": "Bin",
  "department": "Quality Assurance"
  }
]